# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Everything is awesome
email: glennc@microsoft.com
description: >
  Thoughts and experiments from a guy that works no the ASP.NET team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://glennc.github.io" # the base hostname & protocol for your site
twitter_username: condrong
github_username:  glennc

# Build settings
markdown: kramdown
